# Generated by Django 3.0.7 on 2020-07-04 08:29

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('mobile', models.CharField(error_messages={'unique': '该手机号已经注册'}, help_text='11位手机号', max_length=11, unique=True, validators=[account.models.UnicodeMobileValidator()], verbose_name='手机号')),
                ('password', models.CharField(blank=True, error_messages={'max_length': '密码最多128位'}, help_text='本站用户登录使用的密码,三方平台账号登录时无需使用密码', max_length=128, null=True, validators=[account.models.UnicodePasswordValidator()], verbose_name='密码')),
                ('app_key', models.CharField(blank=True, help_text='本站用户注册后拥有,唯一身份标识', max_length=64, unique=True, verbose_name='用户身份key')),
                ('nickname', models.CharField(default='', help_text='昵称', max_length=30, verbose_name='昵称')),
                ('type', models.IntegerField(choices=[(0, '管理员'), (1, '普通用户'), (2, 'vip用户')], default=1, verbose_name='用户类型')),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男')], default=0, help_text='性别', verbose_name='性别')),
                ('avatar', models.ImageField(blank=True, help_text='头像', null=True, upload_to=account.models.upload_avatar, verbose_name='头像')),
                ('getui_client_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='个推客户端ID')),
                ('is_staff', models.BooleanField(default=False, help_text='决定用户能否登录admin管理后台,默认不能', verbose_name='是否职工')),
                ('is_active', models.BooleanField(default=True, help_text='默认激活,当要删除用户时,可以改成False', verbose_name='是否激活')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='姓名', max_length=16, null=True, verbose_name='姓名')),
                ('signature', models.CharField(blank=True, help_text='个性签名', max_length=128, null=True, verbose_name='个性签名')),
                ('birthday', models.CharField(blank=True, help_text='生日', max_length=16, null=True, verbose_name='生日')),
                ('remark', models.TextField(blank=True, help_text='备注', null=True, verbose_name='备注')),
                ('address', models.CharField(blank=True, help_text='家庭住址', max_length=32, null=True, verbose_name='家庭住址')),
                ('user', models.OneToOneField(help_text='连接用户表', on_delete=django.db.models.deletion.CASCADE, related_name='detail', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户详情表',
                'verbose_name_plural': '用户详情表',
            },
        ),
        migrations.CreateModel(
            name='UserAuthModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '手机号密码'), (1, '用户名密码'), (2, '邮箱密码'), (3, '微信'), (4, 'QQ'), (5, '微博')], default=0, help_text='用户认证类型', verbose_name='认证类型')),
                ('identity', models.CharField(help_text='用户登录的标识,如手机号密码登录,则存储手机号,三方平台登录,则存储open_id', max_length=128, unique=True, verbose_name='认证标识')),
                ('is_valid', models.BooleanField(blank=True, help_text='当邮箱密码认证时需要激活', null=True, verbose_name='是否激活')),
                ('password', models.CharField(blank=True, error_messages={'max_length': '密码最多128位'}, help_text='本站用户登录使用的密码,三方平台账号登录时无需使用密码', max_length=128, null=True, verbose_name='密码')),
                ('user', models.ForeignKey(help_text='关联用户', on_delete=django.db.models.deletion.CASCADE, related_name='auths', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户授权表',
                'verbose_name_plural': '用户授权表',
            },
        ),
    ]
